openapi: 3.0.0
info:
    title: Doggii API
    description: API documentation for Doggii application
    version: 1.0.0
paths:
    /shelter/{id}:
        get:
            summary: Get shelter information by ID
            tags:
                - Shelter
            security:
                - bearerAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: string
                      example: "672cd5cace845109a51a1c2e"
            responses:
                200:
                    description: Shelter information retrieved successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: true
                                    payload:
                                        $ref: "#/components/schemas/ShelterData"
                400:
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: false
                                    payload:
                                        type: string
                                        example: Invalid request payload
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: false
                                    payload:
                                        type: string
                                        example: Unauthorized
                403:
                    description: Forbidden
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: false
                                    payload:
                                        type: string
                                        example: Forbidden
                404:
                    description: Not found
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: false
                                    payload:
                                        type: string
                                        example: Shelter not found
                500:
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: false
                                    payload:
                                        type: string
                                        example: Internal server error

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
    schemas:
        ShelterData:
            type: object
            properties:
                id:
                    type: string
                    example: "672cd5cace845109a51a1c2e"
                email:
                    type: string
                    example: "huellitas@gmail.com"
                role:
                    type: string
                    example: "Shelter"
                userName:
                    type: string
                    example: "Ramirovallejos"
                shelterName:
                    type: string
                    example: "Ramiro vallejos"
                status:
                    type: boolean
                    example: true
                createdAt:
                    type: string
                    format: date-time
                    example: "2024-11-07T14:59:22.105Z"
                updatedAt:
                    type: string
                    format: date-time
                    example: "2024-11-12T01:52:26.332Z"

        ErrorResponse:
            type: object
            properties:
                success:
                    type: boolean
                    example: false
                error:
                    type: object
                    properties:
                        message:
                            type: string
                            example: "An error occurred"
                        details:
                            type: string
                            example: "Detailed error message"