openapi: 3.0.0
info:
    title: Doggi API
    description: API documentation for doggi authentication endpoints.
    version: 1.0.0
paths:
    /auth/register:
        post:
            summary: Register a new Adopter
            tags:
                - Auth
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    format: email
                                    example: user@example.com
                                password:
                                    type: string
                                    format: password
                                    example: password123
                            required:
                                - email
                                - password
            responses:
                201:
                    description: User created successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: true
                                    payload:
                                        type: object
                                        properties:
                                            id:
                                                type: string
                                                example: 60d0fe4f5311236168a109ca
                                            email:
                                                type: string
                                                example: user@example.com
                                            role:
                                                type: string
                                                example: Adopter
                400:
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: false
                                    payload:
                                        type: object
                                        properties:
                                            message:
                                                type: string
                                                example: Invalid input
                                            details:
                                                type: string
                                                example: Email is required
                409:
                    description: Conflict
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: false
                                    payload:
                                        type: object
                                        properties:
                                            message:
                                                type: string
                                                example: User already exists
                                            details:
                                                type: string
                                                example: USER_ALREADY_EXISTS
                500:
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: false
                                    payload:
                                        type: object
                                        properties:
                                            message:
                                                type: string
                                                example: Server error
                                            details:
                                                type: string
                                                example: USER_NOT_CREATED

    /auth/register/:
        post:
            summary: Register a new Shelter
            tags:
                - Auth
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    format: email
                                    example: user@example.com
                                password:
                                    type: string
                                    format: password
                                    example: password123
                            required:
                                - email
                                - password
            responses:
                201:
                    description: User created successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: true
                                    payload:
                                        type: object
                                        properties:
                                            id:
                                                type: string
                                                example: 60d0fe4f5311236168a109ca
                                            email:
                                                type: string
                                                example: user@example.com
                                            role:
                                                type: string
                                                example: Shelter
                400:
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: false
                                    payload:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                message:
                                                    type: string
                                                    example: Invalid input
                                                details:
                                                    type: string
                                                    example: Email is required
                409:
                    description: Conflict
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: false
                                    payload:
                                        type: object
                                        properties:
                                            message:
                                                type: string
                                                example: User already exists
                                            details:
                                                type: string
                                                example: USER_ALREADY_EXISTS
                500:
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: false
                                    payload:
                                        type: object
                                        properties:
                                            message:
                                                type: string
                                                example: Server error
                                            details:
                                                type: string
                                                example: USER_NOT_CREATED

    /auth/login:
        post:
            summary: Login a user
            tags:
                - Auth
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    format: email
                                    example: user@example.com
                                password:
                                    type: string
                                    format: password
                                    example: password123
            responses:
                200:
                    description: User logged in successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: true
                                    payload:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: false
                                    payload:
                                        type: object
                                        properties:
                                            message:
                                                type: string
                                                example: Invalid credentials
                                            details:
                                                type: string
                                                example: INVALID_CREDENTIALS
                500:
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: false
                                    payload:
                                        type: object
                                        properties:
                                            message:
                                                type: string
                                                example: Server error
                                            details:
                                                type: string
                                                example: SERVER_ERROR

    